shell = "bash -c '{}'"
default-scheme = "base16-default-dark"

[[items]]
name = "shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = ". \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-fzf"
path = "https://github.com/tinted-theming/tinted-fzf"
themes-dir = "sh"
hook = ". \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24"]

hooks = ["tmux source-file ~/.config/tmux/tmux.conf"]
